### ISSUE TITLE
Conan Update Breaks CI

### ISSUE THREAD

**Issue by rbgodwin-nt** [rhastie/build-nmos-cpp#21]
Ran into a problem with updated Conan 2.0 on my forked repo.  Action failed to build. Correction that worked for me was:

## Install latest versions of CMake and Conan using pip3 package installer
--RUN python3 -m pip install --upgrade pip setuptools wheel cmake conan
++RUN python3 -m pip install --upgrade pip setuptools wheel cmake conan==1.58.0

In the Docker file.  With that change all worked fine.

**Comment by garethsb** [comment]
Yep, still some work to do to get conan 2.0 working, so we should fix to 1.x for now. Conan 1.59 is current 1.x release. We currently need at least 1.47 I think so that would be `'>=1.47,==1.*'` or `~=1.47`.

Could also fix cmake version...
