### ISSUE TITLE
General nmos-cpp questions

### ISSUE THREAD

**Issue by acresp** [rhastie/build-nmos-cpp#27]
Hello

I'm asking these questions on this project because you dockerized all the things... seems that you'd like to make things much easier 🙂 
Is nmos-cpp enough to make some general tests about 2110 virtual routing with devices nodes NMOS IS-04 / IS-05 compliants?
Is it possible make some connections / virtual routing trough a web gui ?
Is there an API to make these connections (I read about the MQTT broker but again, it's not clear for us about the capabilities)

Sorry for these very generic questions but we are begining in 2110, we'd like to make some tests for a future simple project and we think that it would be a good starting point to put the feet in 2110 :-) 

Regards

**Comment by rhastie** [comment]
Let me try and answer these Qs 👍 

1. Is nmos-cpp enough to make some general tests about 2110 virtual routing with devices nodes NMOS IS-04 / IS-05 compliants?

Yes, if you want to run **"virtual"** nodes (ie. no real streams moving around the network). You can run the nmos-cpp registry (default) which has a very basic controller built into on the "/admin" URL and you can then also run one or more nmos nodes using the same container using the RUN_NODE=TRUE switch

2. Is it possible make some connections / virtual routing through a web gui ?

Yes, there is a very basic controller GUI in the container when running in registry mode. Use http://<IP>:8010/admin to access it.

3. Yes. NMOS is an open set of specifications. I suggest you have a read at https://amwa.tv
